[package]
name = "papyrust"
version = "0.1.0"
edition = "2021"

[dependencies]
derive = "1.0.0"
fast_image_resize = { version = "5.1.4", features = ["image"] }
futures = "0.3.31"
iced = { version = "0.13.1", features = ["advanced", "image", "tokio"] }
iced_aw = { version = "0.12.2", features = ["wrap"] }
iced_video_player = { git = "https://github.com/jazzfool/iced_video_player" }
image = "0.25.6"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
shellexpand = "3.1.1"
tokio = { version = "1.45.1", features = ["fs", "net", "rt-multi-thread", "macros", "time", "io-util", "sync"] }
url = "2.5.4"

# Daemon-specific dependencies
smithay-client-toolkit = "0.19"
wayland-client = "0.31"
wayland-protocols = "0.32"
calloop = "0.13"
libmpv = "2.0"
lz4_flex = "0.11"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
memmap2 = "0.9"
anyhow = "1.0"
tempfile = "3.10"
libc = "0.2"
mpv = "0.2.3"

[profile.release]
debug = true

[[bin]]
name = "papyrust-daemon"
path = "src/daemon/main.rs"

[[bin]]
name = "papyrust"
path = "src/main.rs"
