[package]
name = "papyrust"
version = "0.1.0"
edition = "2024"

[dependencies]
derive = "1.0.0"
iced = { version = "0.13.1", features = ["image"] }
iced_video_player = { git = "https://github.com/jazzfool/iced_video_player" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
shellexpand = "3.1.1"
tokio = { version = "1.45.1", features = ["fs", "macros", "rt", "rt-multi-thread"] }
url = "2.5.4"
